language: java

jdk:
  - oraclejdk7
  
before_install:
  - wget https://dl.dropboxusercontent.com/u/58915222/jnlp.jar
  - sudo mkdir -p $JAVA_HOME/sample/jnlp/servlet/
  - sudo mv jnlp.jar $JAVA_HOME/sample/jnlp/servlet/
  - git clone git://github.com/nguillaumin/slick2d-maven.git
  - cd slick2d-maven
  - mvn clean install -q

env:
  global:
    - JAVA_OPTS="-Djava.library.path=../target/natives"