language: java

jdk:
  - oraclejdk7
  
before_script:
  - git clone git://github.com/nguillaumin/slick2d-maven.git
  - cd slick2d-maven
  - mvn clean install

env:
  global:
    - JAVA_OPTS="-Djava.library.path=../target/natives"